name: example
description: A new Flutter project.

publish_to: "none"

version: 1.0.0

environment:
  sdk: ">=3.0.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  file_picker: ^5.3.0
  motion_toast: ^2.6.8
  flutter_dotenv: ^5.0.2
  permission_handler: ^10.2.0
  resend_dart:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - .env
