name: resend_dart
description: Resend Dart SDK
version: 1.0.0
homepage: "https://github.com/devasidmi/resend-dart"

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: ">=3.3.1"

dependencies:
  flutter:
    sdk: flutter
  freezed_annotation: ^2.2.0
  http: ^0.13.6
  json_annotation: ^4.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  freezed: ^2.3.4
  json_serializable: ^6.7.0
  build_runner: ^2.4.4
  very_good_analysis: ^5.0.0+1

flutter:
